Mag/Mag/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page
from django.conf import settings
from users.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',cache_page(60*2)(index), name = 'index' ),
    path('news/', include('users.urls', namespace= 'users') ),
    path('cathedra/', include('cathedra.urls', namespace= 'cathedra') ),

]
if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Mag/cathedra/urls.py
from django.urls import path
from cathedra.views import cathedra, plan, teachers, teachers_data
from django.views.decorators.cache import cache_page
app_name = 'cathedra'

urlpatterns = [
    path('', cache_page(60*2)(cathedra), name = 'cathedra' ),
    path('plan/', cache_page(60*2)(plan), name = 'plan' ),
    path('teachers/', cache_page(60*2)(teachers), name = 'teachers' ),
    path('teachers/data', teachers_data, name='teachers_data')
]

Mag/plan/urls.py
from django.urls import path
from news import views
from .views import *

urlpatterns = [
    path('', plan, name = 'plan_home' )
]

Mag/teachers/urls.py
from django.urls import path,re_path
from teachers import views
from .views import *

urlpatterns = [
    path('', teachers, name = 'teachers_home' ),
    path('data/', teachers_data, name="teachers_data"),
]

Mag/users/urls.py
from django.urls import path
from users.views import news, news_data
from django.views.decorators.cache import cache_page
app_name = 'users'

urlpatterns = [
    path('', cache_page(60*2)(news), name = 'news' ),
    path('data', news_data, name= 'news_data')
]

Mag/cathedra/models.py
from django.db import models
from django.utils.safestring import mark_safe
# Create your models here.


class Teachers(models.Model):
    id = models.AutoField(primary_key=True)
    photo = models.ImageField(blank=True, null = True,default='no-avatar.jpg', verbose_name='Фото сотрудника')
    title = models.CharField(blank=True, null = True,max_length=100,verbose_name='ФИО')
    status = models.CharField(blank=True, null = True,max_length=100,verbose_name='Должность')
    body = models.TextField(blank=True, null = True,verbose_name='О сотруднике')
    date = models.DateTimeField(verbose_name='Дата публикации')

    
    def photo_tag(self):
        # Возвращаем HTML-код с тегом img для отображения уменьшенного изображения в админке
        return mark_safe(f'<img src="{self.photo.url}" style="max-height: 100px;">')
    photo_tag.short_description = 'Фото сотрудника' 

    def __str__(self) :
        return self.title
    
    class Meta:
        verbose_name = 'Сотрудник ВУЗа'
        verbose_name_plural = 'Сотрудники ВУЗа'    

    @property
    def photo_preview(self):
        if self.photo:
            return mark_safe(f'<img src="{self.photo.url}" style="max-height: 300px;">')
        return ""

Mag/plan/models.py
from django.db import models

# Create your models here.

Mag/teachers/models.py
from tabnanny import verbose
from django.db import models

class TeachersAdd(models.Model):
    photo = models.ImageField(blank=True, null = True,upload_to='static/news/downloads', verbose_name='Фото сотрудника')
    title = models.CharField(blank=True, null = True,max_length=100,verbose_name='ФИО')
    status = models.CharField(blank=True, null = True,max_length=100,verbose_name='Должность')
    body = models.TextField(blank=True, null = True,verbose_name='О сотруднике')
    date = models.DateTimeField(verbose_name='Дата публикации')
    class Meta:
        verbose_name = 'Сотрудник ВУЗа'
        verbose_name_plural = 'Сотрудники ВУЗа'
    
    def __str__(self) :
        return self.title

Mag/cathedra/views.py
from django.shortcuts import render
from .models import Teachers
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.core.cache import cache
# Create your views here.


def cathedra(request):
    return render(request, 'cathedra/cathedra.html')

def plan(request):
    return render(request, 'cathedra/plan.html')

def teachers(request):
    return render(request,"cathedra/teachers.html")

def teachers_data(request):
    teachers = Teachers.objects.all()
    page_number = Paginator(teachers, 6).num_pages
    
    cached_teachers = cache.get('teachers_data')
    if cached_teachers:
        return JsonResponse(cached_teachers)
    else:
        data = [{
            "body": t.body,
            "title": t.title,
            "date": t.date,
            "src": t.photo.url,
            "status": t.status,
            "id": t.id
        } for t in teachers]
        cache.set('teachers_data', {"data": data, "pages": page_number}, 60 * 1)
        return JsonResponse({"data": data, "pages": page_number})

Mag/plan/views.py
from django.shortcuts import render

def plan(request):
    return render(request,"plan/plan.html")

Mag/teachers/views.py
from django.shortcuts import render
from .models import TeachersAdd
from django.core.paginator import Paginator
from django.http import JsonResponse

def teachers(request):
    teachers  = TeachersAdd.objects.order_by('date')
    paginator = Paginator(teachers,8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,"teachers/teachers.html",{'teachers':teachers,'page_obj':page_obj})

def teachers_data(request):
    teachers = TeachersAdd.objects.all()
    data = [{
        "body": t.body,
        "title": t.title,
        "date": t.date,
        "src": t.photo.url,
        "status": t.status
    } for t in teachers]
    return JsonResponse({"data": data})

Mag/Mag/templates/cathedra/cathedra.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'cathedra/css/css.css' %}">
    <title>О кафедре</title>
</head>

<body>
    <header class="header">
        <div class="header_img">
            <nav class="nav-bar">
                <div class="logos">
                    <a href="https://mai.ru/">
                        <img src="{% static 'main/img/logo_mai.png' %}" alt="МАИ">
                    </a>
                    <a href="https://mai.ru/">
                        <p class="mai_descr">
                            МАИ
                        </p>
                    </a>
                </div>
                <div class="social">
                    <div class="social_card">
                        <a href="#">
                            <img src="{% static 'main/img/vk.svg' %}" alt="vk">
                        </a>
                    </div>
                    <div class="social_card">
                        <a href="#">
                            <img src="{% static 'main/img/tg.svg' %}" alt="tg">
                        </a>
                    </div>
                    <div class="social_card">
                        <a href="#">
                            <img src="{% static 'main/img/youtube.svg' %}" alt="youtube">
                        </a>
                    </div>
                </div>
                <ul class="nav-bar_list">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'index'  %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:news' %}">Новости</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Подробнее
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'cathedra:cathedra' %}">О кафедре</a></li>
                            <li><a class="dropdown-item" href="{% url 'cathedra:teachers' %}">Преподаватели</a></li>
                            <li><a class="dropdown-item" href="{% url 'cathedra:plan' %}">Учебный план</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </header>
    <article class="intro">
        <div class="div_wrap">
            <div class="intro_card">
                <div class="intro_txt">
                    <h2 class="intro_header">Начало</h2>
                    <p class="intro_desc">История старейшей кафедры университета "Системное моделирование и инженерная
                        графика" ведет отсчет с 1940 года. За это время в аудиториях и лабораториях кафедры было
                        подготовлено более 10 000 специалистов различных областей науки и техники.</p>
                </div>
                <div class="intro_img">
                    <img src="{% static 'cathedra/img/413.jpg' %}" alt="cabinet">
                </div>
            </div>
            <div class="intro_card">
                <div class="intro_img">
                    <img src="{% static 'cathedra/img/men.jpg' %}" alt="men">
                </div>
                <div class="intro_txt">
                    <h2 class="intro_header">Научная деятельность</h2>
                    <p class="intro_desc">Сегодня научные работы кафедры ведутся по следующим направлениям: «Разработка
                        программного обеспечения, электронных коммуникационных устройств», «Проектирование баз данных, и
                        структурированных кабельных систем», «Создание интегрированных информационных комплексов»,
                        «Геометрическое, твердотельное параметрическое и поверхностное моделирование сложных систем и
                        изделий». Научная деятельность кафедры заслужила высокую оценку международных выставках,
                        конференциях и симпозиумах.</p>
                </div>
            </div>
            <div class="intro_card">
                <div class="intro_txt">
                    <h2 class="intro_header">Будущие навыки</h2>
                    <p class="intro_desc">В процессе обучения на кафедре студенты овладевают современными, широко
                        используемыми IT-технологиями: Oracle Database, ОС Unix (Linux, FreeBSD), WEB- инструментами
                        RUBY/PHP/HTML, языком программирования Java, прикладными программами компании Microsoft и
                        1C-Бухгалтерия, а также специальными средствами разработки аппаратного обеспечения: Microchip
                        Technology Inc. и ARM-платформы.</p>
                </div>
                <div class="intro_img">
                    <img src="{% static 'cathedra/img/students.jpg' %}" alt="students">
                </div>
            </div>
            <div class="intro_card">
                <div class="intro_img">
                    <img src="{% static 'cathedra/img/bachelors.jpg' %}" alt="bachelors">
                </div>
                <div class="intro_txt">
                    <h2 class="intro_header">AutoDesk</h2>
                    <p class="intro_desc">
                        Особое внимание уделяется изучению продуктов AutoDesk. На кафедре работают сертифицированные
                        преподаватели, прошедшие обучение в авторизованных учебных центрах компании, в том числе по
                        программе «3D образование». Студенты кафедры неоднократно занимали призовые места и становились
                        лауреатами международных соревнований и конкурсов. Так, в конкурсе "Испытай возможности",
                        проводимом компанией AutoDesk наши студенты заняли призовое 3-е место среди ВУЗов России и стран
                        СНГ.</p>
                </div>
            </div>
        </div>
    </article>
    <script src="{% static 'cathedra/js/script.js' %}"></script>
</body>

</html>

Mag/Mag/templates/cathedra/teachers.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="{% static 'teachers/css/css.css' %}" />
        <title>Преподаватели</title>
    </head>
    <body>
        <header class="header">
            <div class="header_img">
                <nav class="nav-bar">
                    <div class="logos">
                        <a href="https://mai.ru/">
                            <img src="{% static 'main/img/logo_mai.png' %}" alt="МАИ">
                        </a>
                        <a href="https://mai.ru/">
                            <p class="mai_descr">
                                МАИ
                            </p>
                        </a>
                    </div>
                    <div class="social">
                        <div class="social_card">
                            <a href="#">
                                <img src="{% static 'main/img/vk.svg' %}" alt="vk">
                            </a>
                        </div>
                        <div class="social_card">
                            <a href="#">
                                <img src="{% static 'main/img/tg.svg' %}" alt="tg">
                            </a>
                        </div>
                        <div class="social_card">
                            <a href="#">
                                <img src="{% static 'main/img/youtube.svg' %}" alt="youtube">
                            </a>
                        </div>
                    </div>
                    <ul class="nav-bar_list">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'index'  %}">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:news' %}">Новости</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Подробнее
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'cathedra:cathedra' %}">О кафедре</a></li>
                                <li><a class="dropdown-item" href="{% url 'cathedra:teachers' %}">Преподаватели</a></li>
                                <li><a class="dropdown-item" href="{% url 'cathedra:plan' %}">Учебный план</a></li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </header>
        <section class="people">
            <div class="div_wrap">
                <div class="people_wrap">
                </div>
            </div>
        </section>
        <nav class="article_pagination">
            <ul class="article_pagination-list">
            </ul>
        </nav>
        <script src="{% static 'teachers/js/script.js' %}"></script>
    </body>
</html>